
package edu.ucla.grad.commservices.gd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService( wsdlLocation =
             "https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl",
             name = "IProquestFilerService",
             targetNamespace = "http://tempuri.org/" )
@XmlSeeAlso(
  { ObjectFactory.class } )
public interface IProquestFilerService
{


  /**
   *
   * @param gdToken
   * @return
   *     returns edu.ucla.grad.commservices.gd.ReturnResultsForProquestFilers
   */
  @WebMethod( operationName = "GetProquestFilersForAll",
              action = "http://tempuri.org/IProquestFilerService/GetProquestFilersForAll" )
  @Action( input =
           "http://tempuri.org/IProquestFilerService/GetProquestFilersForAll",
           output =
           "http://tempuri.org/IProquestFilerService/GetProquestFilersForAllResponse" )
  @WebResult( name = "GetProquestFilersForAllResult",
              targetNamespace = "http://tempuri.org/" )
  @RequestWrapper( localName = "GetProquestFilersForAll",
                   targetNamespace = "http://tempuri.org/",
                   className = "edu.ucla.grad.commservices.gd.GetProquestFilersForAll" )
  @ResponseWrapper( localName = "GetProquestFilersForAllResponse",
                    targetNamespace = "http://tempuri.org/",
                    className = "edu.ucla.grad.commservices.gd.GetProquestFilersForAllResponse" )
  public ReturnResultsForProquestFilers getProquestFilersForAll( @WebParam( name =
                                                                            "gdToken",
                                                                            targetNamespace =
                                                                            "http://tempuri.org/" )
    String gdToken );

  /**
   *
   * @param proquestID
   * @param gdToken
   * @return
   *     returns edu.ucla.grad.commservices.gd.ReturnResultsForProquestFilersByID
   */
  @WebMethod( operationName = "GetProquestFilerForProquestID",
              action = "http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestID" )
  @Action( input =
           "http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestID",
           output =
           "http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestIDResponse" )
  @WebResult( name = "GetProquestFilerForProquestIDResult",
              targetNamespace = "http://tempuri.org/" )
  @RequestWrapper( localName = "GetProquestFilerForProquestID",
                   targetNamespace = "http://tempuri.org/",
                   className = "edu.ucla.grad.commservices.gd.GetProquestFilerForProquestID" )
  @ResponseWrapper( localName = "GetProquestFilerForProquestIDResponse",
                    targetNamespace = "http://tempuri.org/",
                    className = "edu.ucla.grad.commservices.gd.GetProquestFilerForProquestIDResponse" )
  public ReturnResultsForProquestFilersByID getProquestFilerForProquestID( @WebParam( name =
                                                                                      "gdToken",
                                                                                      targetNamespace =
                                                                                      "http://tempuri.org/" )
    String gdToken,
    @WebParam( name = "proquestID", targetNamespace = "http://tempuri.org/" )
    String proquestID );

}
