
package edu.ucla.grad.commservices.gd;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProquestFilerService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl")
public class ProquestFilerService
    extends Service
{

    private final static URL PROQUESTFILERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.ucla.grad.commservices.gd.ProquestFilerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.ucla.grad.commservices.gd.ProquestFilerService.class.getResource(".");
            url = new URL(baseUrl, "https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROQUESTFILERSERVICE_WSDL_LOCATION = url;
    }

    public ProquestFilerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProquestFilerService() {
        super(PROQUESTFILERSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "ProquestFilerService"));
    }

    /**
     * 
     * @return
     *     returns IProquestFilerService
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IProquestFilerService getWsHttpEndpoint() {
        return super.getPort(new QName("http://tempuri.org/", "wsHttpEndpoint"), IProquestFilerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProquestFilerService
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IProquestFilerService getWsHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsHttpEndpoint"), IProquestFilerService.class, features);
    }

}
