package edu.ucla.grad.commservices.gd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebService(wsdlLocation="https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl",
  targetNamespace="http://tempuri.org/", name="IProquestFilerService")
@XmlSeeAlso(
  { edu.ucla.grad.commservices.gd.ObjectFactory.class })
public interface IProquestFilerService
{
  @WebMethod(operationName="GetProquestFilersForAll", action="http://tempuri.org/IProquestFilerService/GetProquestFilersForAll")
  @Action(input="http://tempuri.org/IProquestFilerService/GetProquestFilersForAll",
    output="http://tempuri.org/IProquestFilerService/GetProquestFilersForAllResponse")
  @ResponseWrapper(localName="GetProquestFilersForAllResponse",
    targetNamespace="http://tempuri.org/", className="edu.ucla.grad.commservices.gd.GetProquestFilersForAllResponse")
  @RequestWrapper(localName="GetProquestFilersForAll", targetNamespace="http://tempuri.org/",
    className="edu.ucla.grad.commservices.gd.GetProquestFilersForAll")
  @WebResult(targetNamespace="http://tempuri.org/", name="GetProquestFilersForAllResult")
  public edu.ucla.grad.commservices.gd.ReturnResultsForProquestFilers getProquestFilersForAll(@WebParam(targetNamespace="http://tempuri.org/",
      name="gdToken")
    String gdToken);

  @WebMethod(operationName="GetProquestFilerForProquestID", action="http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestID")
  @Action(input="http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestID",
    output="http://tempuri.org/IProquestFilerService/GetProquestFilerForProquestIDResponse")
  @ResponseWrapper(localName="GetProquestFilerForProquestIDResponse",
    targetNamespace="http://tempuri.org/", className="edu.ucla.grad.commservices.gd.GetProquestFilerForProquestIDResponse")
  @RequestWrapper(localName="GetProquestFilerForProquestID",
    targetNamespace="http://tempuri.org/", className="edu.ucla.grad.commservices.gd.GetProquestFilerForProquestID")
  @WebResult(targetNamespace="http://tempuri.org/", name="GetProquestFilerForProquestIDResult")
  public edu.ucla.grad.commservices.gd.ReturnResultsForProquestFilersByID getProquestFilerForProquestID(@WebParam(targetNamespace="http://tempuri.org/",
      name="gdToken")
    String gdToken, @WebParam(targetNamespace="http://tempuri.org/", name="proquestID")
    String proquestID);
}
