package edu.ucla.grad.commservices.gd;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebServiceClient(wsdlLocation="https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl",
  targetNamespace="http://tempuri.org/", name="ProquestFilerService")
public class ProquestFilerService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("edu.ucla.grad.commservices.gd.ProquestFilerService");
      URL baseUrl = ProquestFilerService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ProquestFilerService.class.getResource("https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl");
        }
      }
      else
      {
        if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
        wsdlLocationURL =
            new URL(baseUrl, "https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://gd.commservices.grad.ucla.edu/GD.CommServices.ProquestFilerService.svc?wsdl",
          e);
    }
  }

  public ProquestFilerService()
  {
    super(wsdlLocationURL,
          new QName("http://tempuri.org/", "ProquestFilerService"));
  }

  public ProquestFilerService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="wsHttpEndpoint")
  public edu.ucla.grad.commservices.gd.IProquestFilerService getWsHttpEndpoint()
  {
    return (edu.ucla.grad.commservices.gd.IProquestFilerService) super.getPort(new QName("http://tempuri.org/",
                                                                                         "wsHttpEndpoint"),
                                                                               edu.ucla.grad.commservices.gd.IProquestFilerService.class);
  }

  @WebEndpoint(name="wsHttpEndpoint")
  public edu.ucla.grad.commservices.gd.IProquestFilerService getWsHttpEndpoint(WebServiceFeature... features)
  {
    return (edu.ucla.grad.commservices.gd.IProquestFilerService) super.getPort(new QName("http://tempuri.org/",
                                                                                         "wsHttpEndpoint"),
                                                                               edu.ucla.grad.commservices.gd.IProquestFilerService.class,
                                                                               features);
  }
}
